FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-stretch AS build
WORKDIR /src
COPY ["CustomDIWebAPI/CustomDIWebAPI.csproj", "CustomDIWebAPI/"]
RUN dotnet restore "CustomDIWebAPI/CustomDIWebAPI.csproj"
COPY . .
WORKDIR "/src/CustomDIWebAPI"
RUN dotnet build "CustomDIWebAPI.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "CustomDIWebAPI.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "CustomDIWebAPI.dll"]